apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: airflow
  annotations:
    iam.gke.io/gcp-service-account: airflow-gke-sa@PROJECT_ID.iam.gserviceaccount.com