data_lake_bucket_name = "frankfurter-dl"
bigquery_dataset      = "frankfurter_dev"
region                = "europe-west1"
location              = "EU"
zone                  = "europe-west1-b"
vm_name               = "airflow-vm"