name: Terraform CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (sem backend)
        run: terraform init -backend=false -input=false
        
      - name: Terraform Validate
        run: terraform validate

      - name: Authenticate to GCP
        if: github.ref == 'refs/heads/dev'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: github-actions-tf@frankfurter-pipeline.iam.gserviceaccount.com

      - name: Terraform Init (com backend)
        if: github.ref == 'refs/heads/dev'
        run: terraform init -reconfigure

      - name: Terraform Plan
        if: github.ref == 'refs/heads/dev'
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev'
        run: terraform apply -auto-approve -var-file=terraform.tfvars