name: Pipeline CI

on:
  push:
    branches:
      - "**"

jobs:
  test-auth:
    uses: ./.github/workflows/test-auth.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  terraform:
    needs: test-auth
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  airflow:
    needs: terraform
    uses: ./.github/workflows/airflow.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write

  dbt:
    needs: terraform
    uses: ./.github/workflows/dbt.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write