name: Terraform Dev

on:
  push:
    branches:
      - test-ci

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./bootstrap/state

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./bootstrap/state

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./bootstrap/state

  plan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1

      - name: Terraform Init
        run: terraform init
        working-directory: ./bootstrap/state

      - name: Terraform Plan Dev
        run: terraform plan -var-file=terraform.tfvars
        working-directory: ./bootstrap/state

  apply-dev:
    runs-on: ubuntu-latest
    needs: plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1

      - name: Terraform Init
        run: terraform init
        working-directory: ./bootstrap/state

      - name: Terraform Apply Dev
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        working-directory: ./bootstrap/state