name: Terraform CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      apply:
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Debug Bucket
        run: |
          echo "Bucket length: ${{ secrets.GCP_TF_BUCKET && 'set' || 'EMPTY' }}"
          echo "Project: ${{ secrets.GCP_PROJECT_ID }}"

      - name: Terraform Init
        working-directory: ./terraform/infra
        run: terraform init -reconfigure -backend-config="bucket=${{ secrets.GCP_TF_BUCKET }}"

      - name: Terraform Plan
        working-directory: ./terraform/infra
        run: |
          terraform plan \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var-file=terraform.tfvars \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Terraform Apply
        if: inputs.apply == true
        working-directory: ./terraform/infra
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var-file=terraform.tfvars \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Release state lock on failure
        if: failure()
        run: gsutil rm -f gs://${{ secrets.GCP_TF_BUCKET }}/terraform/state/default.tflock || true
